
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeMSYSFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:1 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "make"
    candidate_directories:
      - "C:/Users/acisse/bin/"
      - "C:/Users/acisse/AppData/Local/Programs/Git/mingw64/bin/"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/local/bin/"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/"
      - "C:/Users/acisse/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "C:/Users/acisse/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "C:/Users/acisse/AppData/Local/Programs/Microsoft VS Code/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/Common Files/Pulse Secure/VC142.CRT/X64/"
      - "C:/Program Files (x86)/Common Files/Pulse Secure/VC142.CRT/X86/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Program Files/nodejs/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Program Files/GitHub CLI/"
      - "C:/Users/acisse/.cargo/bin/"
      - "C:/Users/acisse/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/acisse/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/acisse/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/acisse/AppData/Local/Programs/Git/cmd/"
      - "C:/Users/acisse/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/"
      - "C:/Users/acisse/AppData/Local/Microsoft/WinGet/Packages/Anthropic.ClaudeCode_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "C:/Users/acisse/AppData/Local/Programs/Git/"
      - "C:/Users/acisse/AppData/Roaming/npm/"
      - "C:/Users/acisse/AppData/Local/Microsoft/WinGet/Packages/oschwartz10612.Poppler_Microsoft.Winget.Source_8wekyb3d8bbwe/poppler-25.07.0/Library/bin/"
      - "C:/Users/acisse/.vscode/extensions/ms-python.debugpy-2025.18.0-win32-x64/bundled/scripts/noConfigScripts/"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/vendor_perl/"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/core_perl/"
      - "C:/msys32/usr/"
      - "C:/mingw/msys/"
      - "/REGISTRY-NOTFOUND/usr/"
    searched_directories:
      - "C:/Users/acisse/bin/make.com"
      - "C:/Users/acisse/bin/make.exe"
      - "C:/Users/acisse/bin/make"
      - "C:/Users/acisse/AppData/Local/Programs/Git/mingw64/bin/make.com"
      - "C:/Users/acisse/AppData/Local/Programs/Git/mingw64/bin/make.exe"
      - "C:/Users/acisse/AppData/Local/Programs/Git/mingw64/bin/make"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/local/bin/make.com"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/local/bin/make.exe"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/local/bin/make"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/make.com"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/make.exe"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/make"
      - "C:/Users/acisse/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/make.com"
      - "C:/Users/acisse/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/make.exe"
      - "C:/Users/acisse/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/make"
      - "C:/Users/acisse/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/make.com"
      - "C:/Users/acisse/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/make.exe"
      - "C:/Users/acisse/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/make"
      - "C:/Users/acisse/AppData/Local/Programs/Microsoft VS Code/make.com"
      - "C:/Users/acisse/AppData/Local/Programs/Microsoft VS Code/make.exe"
      - "C:/Users/acisse/AppData/Local/Programs/Microsoft VS Code/make"
      - "C:/Windows/System32/make.com"
      - "C:/Windows/System32/make.exe"
      - "C:/Windows/System32/make"
      - "C:/Windows/make.com"
      - "C:/Windows/make.exe"
      - "C:/Windows/make"
      - "C:/Windows/System32/wbem/make.com"
      - "C:/Windows/System32/wbem/make.exe"
      - "C:/Windows/System32/wbem/make"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/make.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/make"
      - "C:/Windows/System32/OpenSSH/make.com"
      - "C:/Windows/System32/OpenSSH/make.exe"
      - "C:/Windows/System32/OpenSSH/make"
      - "C:/Program Files (x86)/Common Files/Pulse Secure/VC142.CRT/X64/make.com"
      - "C:/Program Files (x86)/Common Files/Pulse Secure/VC142.CRT/X64/make.exe"
      - "C:/Program Files (x86)/Common Files/Pulse Secure/VC142.CRT/X64/make"
      - "C:/Program Files (x86)/Common Files/Pulse Secure/VC142.CRT/X86/make.com"
      - "C:/Program Files (x86)/Common Files/Pulse Secure/VC142.CRT/X86/make.exe"
      - "C:/Program Files (x86)/Common Files/Pulse Secure/VC142.CRT/X86/make"
      - "C:/ProgramData/chocolatey/bin/make.com"
      - "C:/ProgramData/chocolatey/bin/make.exe"
      - "C:/ProgramData/chocolatey/bin/make"
      - "C:/Program Files/nodejs/make.com"
      - "C:/Program Files/nodejs/make.exe"
      - "C:/Program Files/nodejs/make"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/make.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/make.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/make"
      - "C:/Program Files/Docker/Docker/resources/bin/make.com"
      - "C:/Program Files/Docker/Docker/resources/bin/make.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/make"
      - "C:/Program Files/GitHub CLI/make.com"
      - "C:/Program Files/GitHub CLI/make.exe"
      - "C:/Program Files/GitHub CLI/make"
      - "C:/Users/acisse/.cargo/bin/make.com"
      - "C:/Users/acisse/.cargo/bin/make.exe"
      - "C:/Users/acisse/.cargo/bin/make"
      - "C:/Users/acisse/AppData/Local/Microsoft/WindowsApps/make.com"
      - "C:/Users/acisse/AppData/Local/Microsoft/WindowsApps/make.exe"
      - "C:/Users/acisse/AppData/Local/Microsoft/WindowsApps/make"
      - "C:/Users/acisse/AppData/Local/Programs/Microsoft VS Code/bin/make.com"
      - "C:/Users/acisse/AppData/Local/Programs/Microsoft VS Code/bin/make.exe"
      - "C:/Users/acisse/AppData/Local/Programs/Microsoft VS Code/bin/make"
      - "C:/Users/acisse/AppData/Local/GitHubDesktop/bin/make.com"
      - "C:/Users/acisse/AppData/Local/GitHubDesktop/bin/make.exe"
      - "C:/Users/acisse/AppData/Local/GitHubDesktop/bin/make"
      - "C:/Users/acisse/AppData/Local/Programs/Git/cmd/make.com"
      - "C:/Users/acisse/AppData/Local/Programs/Git/cmd/make.exe"
      - "C:/Users/acisse/AppData/Local/Programs/Git/cmd/make"
      - "C:/Users/acisse/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/make.com"
      - "C:/Users/acisse/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/make.exe"
      - "C:/Users/acisse/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/make"
      - "C:/Users/acisse/AppData/Local/Microsoft/WinGet/Packages/Anthropic.ClaudeCode_Microsoft.Winget.Source_8wekyb3d8bbwe/make.com"
      - "C:/Users/acisse/AppData/Local/Microsoft/WinGet/Packages/Anthropic.ClaudeCode_Microsoft.Winget.Source_8wekyb3d8bbwe/make.exe"
      - "C:/Users/acisse/AppData/Local/Microsoft/WinGet/Packages/Anthropic.ClaudeCode_Microsoft.Winget.Source_8wekyb3d8bbwe/make"
      - "C:/Users/acisse/AppData/Local/Programs/Git/make.com"
      - "C:/Users/acisse/AppData/Local/Programs/Git/make.exe"
      - "C:/Users/acisse/AppData/Local/Programs/Git/make"
      - "C:/Users/acisse/AppData/Roaming/npm/make.com"
      - "C:/Users/acisse/AppData/Roaming/npm/make.exe"
      - "C:/Users/acisse/AppData/Roaming/npm/make"
      - "C:/Users/acisse/AppData/Local/Microsoft/WinGet/Packages/oschwartz10612.Poppler_Microsoft.Winget.Source_8wekyb3d8bbwe/poppler-25.07.0/Library/bin/make.com"
      - "C:/Users/acisse/AppData/Local/Microsoft/WinGet/Packages/oschwartz10612.Poppler_Microsoft.Winget.Source_8wekyb3d8bbwe/poppler-25.07.0/Library/bin/make.exe"
      - "C:/Users/acisse/AppData/Local/Microsoft/WinGet/Packages/oschwartz10612.Poppler_Microsoft.Winget.Source_8wekyb3d8bbwe/poppler-25.07.0/Library/bin/make"
      - "C:/Users/acisse/.vscode/extensions/ms-python.debugpy-2025.18.0-win32-x64/bundled/scripts/noConfigScripts/make.com"
      - "C:/Users/acisse/.vscode/extensions/ms-python.debugpy-2025.18.0-win32-x64/bundled/scripts/noConfigScripts/make.exe"
      - "C:/Users/acisse/.vscode/extensions/ms-python.debugpy-2025.18.0-win32-x64/bundled/scripts/noConfigScripts/make"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/vendor_perl/make.com"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/vendor_perl/make.exe"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/vendor_perl/make"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/core_perl/make.com"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/core_perl/make.exe"
      - "C:/Users/acisse/AppData/Local/Programs/Git/usr/bin/core_perl/make"
      - "C:/msys32/usr/make.com"
      - "C:/msys32/usr/make.exe"
      - "C:/msys32/usr/make"
      - "C:/mingw/msys/make.com"
      - "C:/mingw/msys/make.exe"
      - "C:/mingw/msys/make"
      - "/REGISTRY-NOTFOUND/usr/make.com"
      - "/REGISTRY-NOTFOUND/usr/make.exe"
      - "/REGISTRY-NOTFOUND/usr/make"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\acisse\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\mingw64\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\usr\\local\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\usr\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\usr\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\mingw64\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\usr\\bin"
        - "C:\\Users\\acisse\\bin"
        - "C:\\Users\\acisse\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
        - "C:\\Users\\acisse\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Microsoft VS Code"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0"
        - "C:\\Windows\\System32\\OpenSSH"
        - "C:\\Program Files (x86)\\Common Files\\Pulse Secure\\VC142.CRT\\X64"
        - "C:\\Program Files (x86)\\Common Files\\Pulse Secure\\VC142.CRT\\X86"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\nodejs"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Program Files\\GitHub CLI"
        - "C:\\Users\\acisse\\.cargo\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\cmd"
        - "C:\\Users\\acisse\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Anthropic.ClaudeCode_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\usr\\bin"
        - "C:\\Windows\\System32"
        - "C:\\Users\\acisse\\AppData\\Roaming\\npm"
        - "C:\\Users\\acisse\\AppData\\Local\\Microsoft\\WinGet\\Packages\\oschwartz10612.Poppler_Microsoft.Winget.Source_8wekyb3d8bbwe\\poppler-25.07.0\\Library\\bin"
        - "C:\\Users\\acisse\\AppData\\Local\\Microsoft\\WinGet\\Packages\\oschwartz10612.Poppler_Microsoft.Winget.Source_8wekyb3d8bbwe\\poppler-25.07.0\\Library\\bin"
        - "C:\\Users\\acisse\\.vscode\\extensions\\ms-python.debugpy-2025.18.0-win32-x64\\bundled\\scripts\\noConfigScripts"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\usr\\bin\\vendor_perl"
        - "C:\\Users\\acisse\\AppData\\Local\\Programs\\Git\\usr\\bin\\core_perl"
...
